# SonarCloud configuration
sonar.organization=cur8d
sonar.projectKey=cur8d.tsx
sonar.projectName=cur8d
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.tsx,tests/**/*.test.ts,tests/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
