sonar.organization=cur8d
sonar.projectKey=cur8d.tsx
sonar.projectName=cur8d
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
